server:
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://localhost/GN
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: test

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true #테이블 생성전, data.sql 실행되는 문제 해결

logging:
  level:
    com.gyub: debug
    org.springframework: debug
    org.hibernate.SQL: debug
    #org.hibernate.type: trace